### PR TITLE
Apple home Website, content and style added

### PR DESCRIPTION
**Pull request by Victorgonbu**
- Html and CSS files added.
- Reset CSS plus media CSS added.
- Apple website content added.
- CSS styles from apple website added.
- Fixed all markup errors.
- Fixed all CSS lint errors.
- Stickler.yml file added.
- Readme file added and filled up.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required!
Hi @Shaqri, great job on this project! :clap: You are meeting most of the requirements. You need to fix one issue to complete this project.
- [x] Your footer appears to be aligned to the right. Please center it as it appears in the [original](https://web.archive.org/web/20140301004610/http://www.apple.com/) site.

__Kindly make the necessary changes and submit another code review request__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__

**Comment by Victorgonbu** [comment]
Hi @trekab, Thank you very much for the code review.
I already made the changes required.

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required!
Hey @Shaqri, I am not able to see your changes in the footer. Here is the [screenshot](https://github.com/trekab/images/blob/master/Shaq/shaq-apple-clone.png?raw=true) of your clone Vs [screenshot](https://github.com/trekab/images/blob/master/Shaq/org-site.png?raw=true) of original site.

If this is different on your side, feel free to reach me on slack so that we can look into this together. Otherwise, try to position the footer accordingly and submit another code review request.

**Comment by Victorgonbu** [comment]
Hi @trekab,
please, excuse me for the misunderstanding, I have finally aligned footer to the center

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
